Repository entelecheia/intronlp-2024, pull requests merged in 2024-09, with the labels that each got.

#28 Entelecheia/issue26
  book/en/_toc.yml
  book/en/week02/index.md
  book/en/week02/session1.md
  book/en/week02/session2.md
  book/ko/_toc.yml
  book/ko/week02/index.md
  book/ko/week02/session1.md
  book/ko/week02/session2.md
Labels: documentation, enhancement, Review effort [1-5]: 4

#31 update team3 proposal
  book/ko/projects/202221014Gyu.md
Labels: documentation, Review effort [1-5]: 1

#32 Main
  book/ko/_toc.yml
  book/ko/projects/index.md
  book/ko/projects/team3/index.md
  book/ko/projects/team3/proposal.md
  book/ko/projects/teams.md
Labels: documentation, enhancement

#35 5조 제안서 업데이트 -홍성관-
  book/ko/projects/team5/index.md
Labels: documentation, Review effort [1-5]: 2

#34 제안서 제출
  book/ko/projects/team1/DPS_proposal.md
Labels: documentation, Review effort [1-5]: 2

#37 Create proposal.md
  book/ko/projects/team4 /proposal.md
Labels: documentation, Review effort [1-5]: 2

#41 Entelecheia/issue40
  book/en/_toc.yml
  book/en/week01/index.md
  book/en/week01/session1.md
  book/en/week01/session2.md
  book/en/week01/wk1-lab1.ipynb
  book/en/week02/index.md
  book/en/week02/session1.md
  book/en/week02/session2.md
  book/en/week02/session3.md
  book/ko/_toc.yml
  book/ko/week01/index.md
  book/ko/week01/session1.md
  book/ko/week01/session2.md
  book/ko/week01/wk1-lab1.ipynb
  book/ko/week02/index.md
  book/ko/week02/session1.md
  book/ko/week02/session2.md
  book/ko/week02/session3.md
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, Review effort [1-5]: 4

#42 Main
  book/en/_toc.yml
  book/en/week01/index.md
  book/en/week01/session1.md
  book/en/week01/session2.md
  book/en/week01/wk1-lab1.ipynb
  book/en/week02/index.md
  book/en/week02/session1.md
  book/en/week02/session2.md
  book/en/week02/session3.md
  book/ko/_toc.yml
  book/ko/week01/index.md
  book/ko/week01/session1.md
  book/ko/week01/session2.md
  book/ko/week01/wk1-lab1.ipynb
  book/ko/week02/index.md
  book/ko/week02/session1.md
  book/ko/week02/session2.md
  book/ko/week02/session3.md
  poetry.lock
  pyproject.toml
Labels: documentation, enhancement, Review effort [1-5]: 4

#46 teem5 proposal update
  book/ko/projects/team5/proposal.md
Labels: documentation, Review effort [1-5]: 2

#47 feat: update team2 proposal.md by ypilseong
  book/ko/projects/team2/proposal.md
Labels: documentation, Review effort [1-5]: 2

#57 Create W1.md
  book/ko/projects/team4/Research-Log/W1.md
Labels: documentation, Review effort [1-5]: 1

#58 Create W2.md
  book/ko/projects/team4/Research-Log/W2.md
Labels: Review effort [1-5]: 1

#59 Update proposal and researchnote 3week
  book/ko/projects/team3/proposal.md
  book/ko/projects/team3/research-note3w.md
Labels: documentation, Review effort [1-5]: 2

#62 Update new member
  book/ko/projects/team3/proposal.md
Labels: documentation, Review effort [1-5]: 1

#63 연구일지 1주차 추가
  book/ko/projects/team1/0904.md
  book/ko/projects/team1/0905.md
  book/ko/projects/team1/0909.md
Labels: documentation, Review effort [1-5]: 2

#66 add research-note-day1, 2, 3 by hxngo team5
  book/ko/projects/team5/index.md
  book/ko/projects/team5/proposal.md
  book/ko/projects/team5/research-note-day1, 2, 3.md
Labels: documentation, Review effort [1-5]: 2

#67 202021017, add research note and update team member by Maenjh
  book/ko/projects/team1/0911.md
  book/ko/projects/team1/index.md
  book/ko/projects/team1/proposal.md
Labels: documentation, Review effort [1-5]: 2

#72 202021017/fix: resolve issue causing function to not execute
  book/ko/week02/session3.md
Labels: enhancement, Review effort [1-5]: 2, Bug fix

#73 Main
  book/ko/week02/session3.md
  poetry.lock
  pyproject.toml
Labels: enhancement, Bug fix, dependencies

#91 Week 4 Session 2 - Advanced word embedding code modification
  book/ko/week04/session2.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#90 Week 3 Session 1 - Revised language model and N-gram introduction
  book/ko/week03/session1.md
Labels: documentation, enhancement, Review effort [1-5]: 2

#93 Create W3.md
  book/ko/projects/team4/Research-Log/W3.md
Labels: documentation, Review effort [1-5]: 1

#75 fix: resolved code execution issue
  book/ko/week03/session2.md
Labels: enhancement, Review effort [1-5]: 3, Bug fix

#74 fix: resolve issue causing function to not execute
  book/ko/week02/session2.md
Labels: documentation, enhancement, Review effort [1-5]: 3

#105 Team 5 5th research log uploaded
  book/ko/projects/team5/research-note-4.md
  book/ko/projects/team5/research-note-5.md
Labels: documentation, Review effort [1-5]: 2

#107 Week 5 1 session code update
  book/ko/week05/session1.md
Labels: documentation, enhancement, Review effort [1-5]: 2
