Repository entelecheia/intronlp-2024, pull requests merged in 2024-10, with the labels that each got.

#119 Create W5.md
  book/ko/projects/team4/Research-Log/W5.md
Labels: documentation, Review effort [1-5]: 2

#118 Create W4.md
  book/ko/projects/team4/Research-Log/W4.md
Labels: documentation, Review effort [1-5]: 1

#140 Team 5's 8th research log uploaded
  book/ko/projects/team5/research-note-8.md
Labels: documentation, Review effort [1-5]: 1

#139 Team 5's 7th research log uploaded
  book/ko/projects/team5/research-note-7.md
Labels: Review effort [1-5]: 1

#152 Create research-note-9.md
  book/ko/projects/team5/research-note-9.md
Labels: documentation, Review effort [1-5]: 2
